<?php

$config = array(
	"base_url"               => "http://localhost:8080/",
	"home_url"               => "https://blakey.family",
	"db_host"                => "localhost",
	"db_username"            => "mysql_user",
	"db_password"            => "mysql_strong_password",
	"db_name"                => "mysql_database",
	"repeat_headings"        => true,
	"software_name"          => "Pollererer Attendance",
	"smtp_host"              => "",
	"smtp_username"          => "",
	"smtp_password"          => "",
	"smtp_port"              => 0,
	"smtp_encryption"        => "ssl",
	"send_emails"            => array(1),
	"email_from"             => "attendance@pollererer.com",
	"email_pdf"              => array(),
	"admin_email"            => "spam@adamblakey.co.uk",
	"logo_url"               => "https://attendance.nsw.org.uk/uploads/logo-horizontal.png",
	"group_name"             => "Pollererer Test",
	"hide_past_dates"        => false,
	"hide_instrument"        => false,
	"taxonomy_rehearsal"     => "rehearsal",
	"taxonomy_rehearsals"    => "rehearsals",
	"taxonomy_concert"       => "concert",
	"taxonomy_ensemble"      => "ensemble",
	"taxonomy_ensembles"     => "ensembles",
	"software_name"          => "Pollererer",
	"assume_attending"       => true,
	"email_before_rehearsal" => 1.5 * 60 * 60,
	"email_before_concert"   => 5   * 60 * 60,
);
