<?php
	require_once($_SERVER['DOCUMENT_ROOT']."/includes/class.members.php");

	function create_sql_database()
	{
		$sql  = '-- Autogenerated SQL by Pollererer';
		$sql .= '';
		$sql .= 'SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";';
		$sql .= 'SET AUTOCOMMIT = 0;';
		$sql .= 'START TRANSACTION;';
		$sql .= 'SET time_zone = "+00:00";';

		// ************* //
		// Member table. // 
		// ************* //
		$sql .= 'CREATE TABLE `attendance` (';

		$member_properties = get_class_vars(member);
		foreach ($member_properties as $property)
		{
			$sql .= ''
		}

		$sql .= ') ENGINE=InnoDB DEFAULT CHARSET=utf8;';
	}
?>